// <auto-generated />
using System;
using GestionDeDevoluciones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeDevoluciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227225427_AddDecisionAndObservacionToRemito")]
    partial class AddDecisionAndObservacionToRemito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDeDevoluciones.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ClienteId");

                    b.HasIndex("DireccionId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.DecisionAdoptada", b =>
                {
                    b.Property<int>("DecisionAdoptadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecisionAdoptadaId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.HasKey("DecisionAdoptadaId");

                    b.HasIndex("PersonalId");

                    b.ToTable("DecisionesAdoptadas");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Direccion", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DireccionId"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DireccionId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Observaciones", b =>
                {
                    b.Property<int>("ObservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservacionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.HasKey("ObservacionId");

                    b.HasIndex("PersonalId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Personal", b =>
                {
                    b.Property<int>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalId"));

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PersonalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("CV")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Const")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Protec")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RPM")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RemitoId")
                        .HasColumnType("int");

                    b.Property<string>("Voltaje")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Remito", b =>
                {
                    b.Property<int>("RemitoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemitoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("DecisionAdoptadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ObservacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("RemitoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DecisionAdoptadaId");

                    b.HasIndex("ObservacionId");

                    b.HasIndex("TipoEstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.TipoEstado", b =>
                {
                    b.Property<int>("TipoEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEstadoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoEstadoId");

                    b.ToTable("TiposEstado");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Cliente", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Direccion", "Direccion")
                        .WithOne()
                        .HasForeignKey("GestionDeDevoluciones.Models.Cliente", "DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.DecisionAdoptada", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Personal", "Personal")
                        .WithMany("DecisionesAdoptadas")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Observaciones", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Personal", "Personal")
                        .WithMany("Observaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Personal", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Producto", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Remito", "Remito")
                        .WithMany("Productos")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Remito", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionDeDevoluciones.Models.DecisionAdoptada", "Decision")
                        .WithMany()
                        .HasForeignKey("DecisionAdoptadaId");

                    b.HasOne("GestionDeDevoluciones.Models.Observaciones", "Observacion")
                        .WithMany()
                        .HasForeignKey("ObservacionId");

                    b.HasOne("GestionDeDevoluciones.Models.TipoEstado", "TipoEstado")
                        .WithMany()
                        .HasForeignKey("TipoEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionDeDevoluciones.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Decision");

                    b.Navigation("Observacion");

                    b.Navigation("TipoEstado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Usuario", b =>
                {
                    b.HasOne("GestionDeDevoluciones.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Personal", b =>
                {
                    b.Navigation("DecisionesAdoptadas");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("GestionDeDevoluciones.Models.Remito", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
